### ISSUE TITLE
Question about serving Hammer models with vllm's function calling feature

### ISSUE THREAD

**Issue by jc-ryan** [MadeAgents/Hammer#5]
Great work on the Hammer project! 👏

I noticed that some models in the Hammer 2.0 series are fine-tuned based on qwen2.5, while others are based on qwen2.5-coder. I have a question regarding their deployment using vllm:

Can all these models utilize vllm's built-in function calling feature during deployment, similar to qwen2.5? For example, like this command:
```bash
vllm serve Qwen/Qwen2.5-7B-Instruct --enable-auto-tool-choice --tool-call-parser hermes
```
(Reference: https://qwenlm.github.io/zh/blog/qwen2.5/)

Or do we need to modify parameters like --tool-call-parser for different Hammer models?
Thank you in advance for your clarification!

**Comment by linqq9** [comment]
Thank you for your question! Currently, we do not support the direct invocation of the tool-call function by vllm. However, we appreciate your reminder, which has drawn our attention to this aspect. 😊

**Comment by jc-ryan** [comment]
> Thank you for your question! Currently, we do not support the direct invocation of the tool-call function by vllm. However, we appreciate your reminder, which has drawn our attention to this aspect. 😊

I see, thank you! May I ask what work needs to be done to support direct inference with vllm? Perhaps I could contribute to this effort?

**Comment by linqq9** [comment]
Thank you so much for your kind offer! We truly appreciate your enthusiasm and eagerness to contribute. Currently, we are still in the process of researching how to support direct inference with vllm as well as refactoring our release code. Once we gain a clearer understanding and have a solid plan in place, we will surely keep you informed. Thank you again for your interest!

**Comment by jc-ryan** [comment]
Looking forward to the upcoming update. Thanks for working on this!

**Comment by linqq9** [comment]
Hi, the latest Hammer2.1 system models have been updated and now support vllm's built-in function calling. You can deploy these models using vllm with the function calling feature enabled, just like the example you mentioned before. Additionally, you can also make function calls using the Hammer client.
