### ISSUE TITLE
Introduction of RoTBench

### ISSUE THREAD

**Issue by Junjie-Ye** [MadeAgents/Hammer#9]
I am glad to see that you have focused on the lack of robustness of LLMs in tool learning and proposed improvements, in fact, we raised the issue about robustness of tool learning and gave a solution based on environment augmentation in our January paper [*RoTBench: A Multi-Level Benchmark for Evaluating the Robustness of Large Language Models in Tool Learning*](https://arxiv.org/abs/2401.08326), which has been accepted by EMNLP2024, and I hope that it will be helpful for your research.

**Comment by linqq9** [comment]
Thank you very much for sharing your paper and solution. 
We highly welcome you to have a trial of our models and experience their effects.
